### ISSUE TITLE
Scientific_name and tax_id for blanks

### ISSUE THREAD

**Issue by cpavloud** [emo-bon/sequencing-profile#2]
I think the usage of "unidentified" as a scientific_name for the blanks is wrong, since it is much more vague than it should be. 
I believe the term "[metagenome](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=256318)" fits just fine (and the respective tax_id: 256318). 
This is what I have used for the manual sample registration of batch 1 and batch 2.
Not sure who to tag for this issue, but @kmexter I am tagging you just to keep an eye.

**Comment by kmexter** [comment]
Noted - we will have to update the logsheets as they are now, perhaps also update/add a drop-down menu, and update the defnitions tab

**Comment by melanthia** [comment]
we will do the updates today

**Comment by melinalou** [comment]
One question:
for example here https://docs.google.com/spreadsheets/d/1VATpzmhwmk8sYkhEjCbDUZHRiYuNGpSRefhXthZRbfQ/edit?gid=1331197248#gid=1331197248 at 132 line it has empty tax_id but has marine plankton metagenome in scientific_name. In this case what we should do?

**Comment by cpavloud** [comment]
> One question:
for example here https://docs.google.com/spreadsheets/d/1VATpzmhwmk8sYkhEjCbDUZHRiYuNGpSRefhXthZRbfQ/edit?gid=1331197248#gid=1331197248 at 132 line it has empty tax_id but has marine plankton metagenome in scientific_name. In this case what we should do?

If the "scientific_name" is "[marine plankton metagenome](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=1874687)" then the "tax_id" should be "1874687" (as is in previous lines). 
So all the empty lines that refer to "marine plankton metagenome" should be filled in accordingly. 

The term "unidentified" should be replaced with "[metagenome](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=256318)" (and the respective tax_id should be 256318).

**Comment by melinalou** [comment]
Ι see!Thank you.

**Comment by melinalou** [comment]
done, please have a look at one logsheets to be sure that is right.

**Comment by melinalou** [comment]
I don't have permission to close the issue

**Comment by kmexter** [comment]
done
